# Copyright © 2014 Petr Zelenin <po.zelenin@gmail.com>
#
# Distributed under terms of the MIT license.

language: python

notifications:
  email: 'po.zelenin@gmail.com'
  irc:
    channels:
      - "chat.freenode.net#sacrud"
    on_success: change
    on_failure: always

python:
  - '2.7'

install:
  - pip install nose coveralls
  - pip install pyramid
  - pip install git+https://github.com/ITCase/sacrud.git@develop
  - pip install git+https://github.com/ITCase/pyramid_sacrud.git@develop
  - pip install -r requirements.txt

script:
  - nosetests --with-coverage --cover-package pyramid_sacrud_gallery --cover-erase --with-doctest

after_success:
  coveralls
